version: "3"
services:
  server:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    environment:
      - CLICKHOUSE_DB=test
      - CLICKHOUSE_USER=dev
      - CLICKHOUSE_PASSWORD=1231234
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
